version: '3.1'

services:
  cfe-docker:
    container_name: cfe-docker
    hostname: cfe_docker
    build:
      context: .
      dockerfile: ./Dockerfile
    image: cfe-docker:dev
    command: '"/usr/sbin/sshd" "/etc/init.d/apache2 start"'